version: "2"

services:
  app:
    image: python:latest
    environment:
      - LANG='en_US.UTF-8'
      - PYTHONDONTWRITEBYTECODE=1
    tty: true
    command: /bin/bash
    working_dir: /root/
    volumes:
      - ./:/root/
    command: |
      bash -c "\
      bash"
    links:
      - postgres:postgres
      - mariadb:mariadb

    privileged: true

  postgres:
    image: postgres:latest
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      # POSTGRES_DB: postgres
    volumes:
      - ./data/postgresql/:/var/lib/postgresql/
    expose:
      - "5432"

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: mysql
    volumes:
      - ./data/mysql/:/var/lib/
    expose:
      - "3306"
